---
params:
        o: 'NA'
        v: 'NA'
        t: 'NA'
        n: 'NA'
        dat: 'NA'
        name: 'NA'
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
output: pdf_document
classoption: landscape        
tables: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "latex")
library(kableExtra)
```

# Power analysis report for a `r params$t`  
Report generated on `r format(Sys.Date(), "%B %d, %Y")`  

****

## Results of the power analysis:  
  
```{r results = 'asis'}
kable(params$o, booktabs = T)
```
\newline    

### Analysis Notes  

```{r results = 'asis'}
cat(paste("<p>", params$n$notes, "</p>"), 
    sep = "\n")
```

### Reported Variables  

```{r results = "asis"}
cat(paste("<p>", params$v$variables, "</p>"), 
    sep = "\n")
```

****  

### Inputs to Analysis  
This analysis was generated with the following user-provided pilot data:  
Source file: `r params$name`  

```{r results = 'asis'}
a<-knitr::kable(params$dat, booktabs = T)
kable_styling(a, latex_options = "scale_down")
```




